- hosts: postgres-dependent
  tasks:
    - name: Change hostname to postgres-dependent
      command: hostnamectl set-hostname postgres-dependent
      become: yes

    - name: Edit hostname to /etc/hostname 
      lineinfile:
        dest: /etc/hostname  
        regexp: '^ip*'
        line: 'postgres-dependent'
        state: present  
      become: yes

    - name: Add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost postgres-dependent'
        state: present  
      become: yes

    - name: Install docker dependencies
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: true
      become: yes
      with_items:
        - "ca-certificates"
        - "curl"
        - "gnupg"
        - "lsb-release"
        - "python3-pip"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: yes

    - name: Install Docker Module for Python
      pip:
        name: docker
      become: yes

    - name: Pull Java Docker image
      community.docker.docker_image:
        name: openjdk
        source: pull
      become: yes
